#### general settings
name: d5.manual.resize960x512
use_tb_logger: true
model: video_base
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: d5.manual.resize960x512
    mode: video_samesize
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: ../datasets/d5/train.down2/GT
    dataroot_LQ: ../datasets/d5/train.down2/input
    cache_keys: ~
    cache_data: true
    padding: new_info

    N_frames: 5     # how many frames as a input.
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 32
    GT_size: 128     # size you want to crop out as input sample.
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS4
    mode: video_test
    dataroot_GT: ../datasets/d4/eval.resize960x512/GT
    dataroot_LQ: ../datasets/d4/eval.resize960x512/input
    cache_data: true
    N_frames: 5
    padding: new_info

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5      # must be same as N_frames in dataset.
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: true     # default false
  HR_in: true       # true if size(input) == size(HR)
  w_TSA: true

#### path
path:
  pretrain_model_G: null
  # pretrain_model_G: ../experiments/pretrained_models/EDVR_REDS_SR_M_woTSA.pth
  strict_load: false
  resume_state: null
  # resume_state: /data1/why/EDVR/experiments/001_from_RDVR_M_samesizeVideo_as_input/training_state/200000.state
  # resume_state: /data1/why/EDVR/experiments/d4.manual.resize960x512/training_state/35000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual.resize960x512_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
